- KickBoardApp/Controller/EditController.swift
- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/Controller/MypageController.swift
- KickBoardApp/Controller/TabBarContorller.swift
- KickBoardApp/SceneDelegate.swift
TabBarController & ViewContoroller 추가
<br><br>
TabBarController & ViewContoroller 추가
<br><br>
추후 로그인 페이지 구현 시 rootController 재설정
<br><br>
없음
<br><br>
> Feat: TabBarController & 하위 Controller 추가

- KickBoardApp.xcodeproj/project.pbxproj
xcode 프로젝트 파일 구성요소
<br><br>
xcode 프로젝트 파일 구성요소
<br><br>
폴더 구조나 파일 바뀌면 커밋 해줘야 되나봄
<br><br>
없음
<br><br>
> Fix: 프로젝트파일 구성요소 재업로드

- .gitignore
- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KickBoardApp.xcodeproj/xcuserdata/kdh.xcuserdatad/xcschemes/xcschememanagement.plist
- KickBoardApp/Controller/TabBarContorller.swift
- KickBoardApp/Info.plist
- KickBoardApp/Model/Model.swift
- KickBoardApp/View/HomeView.swift
초기 세팅 수정
<br><br>
생성
Model/Model.swift
View/HomeView.swift
수정
Controller/TabBarContorller.swift
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Refactor: 초기 세팅 수정

- KickBoardApp/Controller/JoinController.swift
- KickBoardApp/Controller/LoginController.swift
- KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
- KickBoardApp/Model/User+CoreDataClass.swift
- KickBoardApp/Model/User+CoreDataProperties.swift
- KickBoardApp/View/JoinView.swift
성별 선택기능 구현
<br><br>
성별 선택기능 구현
<br><br>
<br><br>
<br><br>
> Feat: 성별 선택기능 구현

- KickBoardApp/Controller/JoinController.swift
- KickBoardApp/Controller/LoginController.swift
- KickBoardApp/View/JoinView.swift
- KickBoardApp/View/LoginView.swift
로그인 시 UserDefaults 에 저장
<br><br>
로그인 시 UserDefaults 에 저장
<br><br>
<br><br>
<br><br>
> Feat: 로그인 시 UserDefaults 에 저장

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/UserProfiles/RegisterHistoryController.swift
- KickBoardApp/Controller/UserProfiles/UsageHistoryController.swift
- KickBoardApp/View/UserProfiles/RegisterCell.swift
- KickBoardApp/View/UserProfiles/RegisterHistoryView.swift
컬레션뷰 셀꾸몄슴다
<br><br>
컬레션뷰 셀꾸몄슴다
<br><br>
컬레션뷰 셀꾸몄슴다
<br><br>
- Close #이슈번호
<br><br>
> Feat: 셀꾸미기

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KickBoardApp/View/HomeView.swift
Git Conflict 해결 commit
<br><br>
Fix: Git Conflict 해결 commit
<br><br>
파일 이름 변경으로 인한 Conflict
HomeView -> MapView
<br><br>
- Close #이슈번호
<br><br>
> Fix: Git Conflict 해결 commit

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/UserProfiles/MypageController.swift
- KickBoardApp/Model/DataManager.swift
- KickBoardApp/View/UserProfiles/MyPageView.swift
Data Manager 추가
<br><br>
Data Manager 추가
<br><br>
Data Manager 추가
<br><br>
- Close #이슈번호
<br><br>
> Feat: DataManager

- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/View/HomeView.swift
Refactor: view랑 viewController 분리
<br><br>
Refactor: view랑 viewController 분리
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Refactor: view랑 viewController 분리

- KickBoardApp/Model/DataManager.swift
데이터 메니저 에러 고쳤습니다.
<br><br>
데이터 메니저 에러 고쳤습니다.
<br><br>
데이터 메니저 에러 고쳤습니다.
<br><br>
- Close #이슈번호
<br><br>
> Fix: DataManagerError

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
- KickBoardApp/Model/KickBoard+CoreDataProperties.swift
- KickBoardApp/Model/Ride+CoreDataClass.swift
- KickBoardApp/Model/Ride+CoreDataProperties.swift
- KickBoardApp/Model/User+CoreDataClass.swift
- KickBoardApp/Model/User+CoreDataProperties.swift
이용내역 coreData 생성
<br><br>
이용내역 coreData 생성
<br><br>
이용내역 coreData 생성
<br><br>
<br><br>
> Refactor: 이용내역 coreData 생성

- KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
- KickBoardApp/Model/KickBoard+CoreDataClass.swift
- KickBoardApp/Model/Ride+CoreDataClass.swift
- KickBoardApp/Model/User+CoreDataClass.swift
엔티티 파일 수정
<br><br>
엔티티 파일 수정
<br><br>
<br><br>
<br><br>
> Fix: 엔티티 파일 수정

- KickBoardApp/Model/Ride+CoreDataProperties.swift
Fix: 오류 수정
<br><br>
Fix: 오류 수정
<br><br>
Fix: 오류 수정
<br><br>
<br><br>
> Fix: 오류 수정

- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/Controller/LoginController.swift
- KickBoardApp/Controller/MapController.swift
- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Controller/UserProfiles/MypageController.swift
- KickBoardApp/Controller/UserProfiles/RegisterHistoryController.swift
- KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
- KickBoardApp/Model/DataManager.swift
- KickBoardApp/Model/KickBoard+CoreDataClass.swift
- KickBoardApp/Model/KickBoard+CoreDataProperties.swift
- KickBoardApp/SceneDelegate.swift
- KickBoardApp/View/RegisterKickboardView.swift
- KickBoardApp/View/UserProfiles/MyPageView.swift
Reverts Kim-Dong-Hyeon/KickBoardApp#34
> Revert "Cg"

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/JoinController.swift
- KickBoardApp/Controller/LoginController.swift
키보드 내리는 기능 구현
<br><br>
키보드 내리는 기능 구현
<br><br>
키보드 내리는 기능 구현
<br><br>
<br><br>
> Feat: 키보드 내리는 기능 구현

- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Model/AnimaitionButton.swift
- KickBoardApp/View/HomeView.swift
- KickBoardApp/View/RegisterKickboardView.swift
Fix: RegisterKickboardView내 MabView 사용방법 변경
<br><br>
Fix: RegisterKickboardView내 MabView 사용방법 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: RegisterKickboardView내 MabView 사용방법 변경

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/UserProfiles/MypageController.swift
- KickBoardApp/Controller/UserProfiles/UsageHistoryController.swift
- KickBoardApp/View/UserProfiles/ExpandableCell.swift
- KickBoardApp/View/UserProfiles/UsageListCell.swift
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: cell, logOut

- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/Controller/MapController.swift
- KickBoardApp/View/HomeView.swift
홈탭에 서치바 삭제 / 위치정보 레이블 삽입
<br><br>
홈탭에 서치바 삭제 / 위치정보 레이블 삽입
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Feat: 홈탭에 서치바 삭제 / 위치정보 레이블 삽입

- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/View/HomeView.swift
- KickBoardApp/View/RegisterKickboardView.swift
HomeView, RegisterKickboardView UI 수정
<br><br>
HomeView, RegisterKickboardView UI 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: HomeView, RegisterKickboardView UI 수정

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Model/AddressFetcher.swift
- KickBoardApp/Model/LocationManager.swift
Fix: 주소받아오는 방식 변경
Fix: 주소받아오는 방식 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: 주소받아오는 방식 변경

- KickBoardApp/AppDelegate.swift
- KickBoardApp/Info.plist
- KickBoardApp/Model/AddressFetcher.swift
Fix: APIKey 수정
<br><br>
Fix: APIKey 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: APIKey 수정

- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Model/AddressFetcher.swift
Fix: KickBoardCoreData 내 좌표부분 추가
<br><br>
Fix: KickBoardCoreData 내 좌표부분 추가
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: KickBoardCoreData 내 좌표부분 추가

- KickBoardApp.xcodeproj/project.pbxproj
- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/Controller/MapController.swift
- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Controller/TabBarContorller.swift
- KickBoardApp/Info.plist
- KickBoardApp/Model/AddressFetcher.swift
- KickBoardApp/Model/DataManager.swift
- KickBoardApp/Model/LocationManager.swift
- KickBoardApp/Model/RegionFetcher.swift
- KickBoardApp/View/HomeView.swift
- KickBoardApp/View/MapView.swift
- KickBoardApp/View/RegisterKickboardView.swift
Fix: 킥보드 등록 페이지 키보드 내리기 액션 추가
Add: RegionFetcher 추가
Refactor: MapController 활용부분 리펙토링
Fix: readCurrentAddress 좌표방식으로 수정 고침
Fix: 위도 경도 값으로 newKickboard 등록 변경
Feat: modalAddressLabel poi 좌표 주소 적용
Fix: RegisterKickboardController 현위치 버튼 zoomLevel 수정
Refactor: Map 관련 class 리펙토링
Style: CodeConvention 적용(Map 관련 파일)
Comment: 메서드 설명 주석 추가(Map 관련 부분)
Chore: 팀 setting 으로 변경
<br><br>
킥보드 등록 페이지 키보드 내리기 액션 추가
RegionFetcher 추가
MapController 활용부분 리펙토링
readCurrentAddress 좌표방식으로 수정 고침
위도 경도 값으로 newKickboard 등록 변경
modalAddressLabel poi 좌표 주소 적용
RegisterKickboardController 현위치 버튼 zoomLevel 수정
Map 관련 class 리펙토링
CodeConvention 적용(Map 관련 파일)
메서드 설명 주석 추가(Map 관련 부분)
팀 setting 으로 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Kdh to develop PR

- KickBoardApp/Model/AddressFetcher.swift
Fix: 주소 앞 부분 제거
<br><br>
Fix: 주소 앞 부분 제거
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: 주소 앞 부분 제거

- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/View/RegisterKickboardView.swift
킥보드 등록페이지 UI 수정
<br><br>
킥보드 등록페이지 UI 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: 킥보드 등록페이지 UI 수정

- KickBoardApp/View/RegisterKickboardView.swift
- KickBoardApp/View/UserProfiles/MyPageView.swift
Design: 마이페이지 UI 일부 수정
<br><br>
Design: 마이페이지 UI 일부 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: 마이페이지 UI 일부 수정

- KickBoardApp/Controller/HomeController.swift
- KickBoardApp/Controller/MapController.swift
- KickBoardApp/Controller/RegisterKickboardController.swift
- KickBoardApp/Controller/UserProfiles/MypageController.swift
- KickBoardApp/Model/Model.swift
- KickBoardApp/View/UserProfiles/MyPageView.swift
킥보드 반납 기능 추가
<br><br>
킥보드 반납 기능 추가
<br><br>
킥보드 반납 기능 추가
<br><br>
- Close #이슈번호
<br><br>
> Feat: 킥보드 반납 기능 추가

- KickBoardApp/View/UserProfiles/MyPageView.swift
Fix: 마이페이지 오류
<br><br>
Fix: 마이페이지 오류
<br><br>
Fix: 마이페이지 오류
<br><br>
- Close #이슈번호
<br><br>
> Fix: 마이페이지 오류
